sonar.projectKey=ChipanaFadiley_ucv-ate-si-lab08
sonar.organization=chipanaadiley
sonar.projectName=ucv-ate-si-lab08

sonar.sources=agente_ucv
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
